language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.6"
env:
  - DJANGO_VERSION=">=1.7,<1.8"
  - DJANGO_VERSION=">=1.8,<1.9"
  - DJANGO_VERSION=">=1.9,<1.10"
  - DJANGO_VERSION=">=1.10,<1.11"
install: "pip install Django$DJANGO_VERSION"
script: python run_tests.py
